# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G

mod_id=eyeofdragonsreborn
mod_name=Eye of Dragons Reborn
mod_version=1.3.0
mod_group_id=iafeyes.eyeofdragonsreborn
mod_authors=FromtheArakiel
mod_license=GPL 3.0
mod_description=Adds Eye of Dragons to find Ice, Fire and Lightning dragons

minecraft_version=1.20.1
forge_version=47.4.10
